// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhdjkfjacsvjtiivogtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZGprZmphY3N2anRpaXZvZ3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDE5MDAsImV4cCI6MjA2NzExNzkwMH0.QWpcEnUY0lp-bcCVhL8YR4zXWPsMwsDG-OW5ZWJ33eM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});